### ISSUE TITLE
Add support for ruby 2.2.1 on Windows

### ISSUE THREAD

**Issue by topac** [codahale/bcrypt-ruby#116]
hi, bcrypt does not work on `ruby 2.2.1p85 (2015-02-26 revision 49769) [i386-mingw32]` (windows server 2008)

```
C:\test\test-db>gem install bcrypt
Successfully installed bcrypt-3.1.10-x86-mingw32
Parsing documentation for bcrypt-3.1.10-x86-mingw32
Done installing documentation for bcrypt after 0 seconds
1 gem installed

C:\test\test-db>irb
irb(main):001:0> require 'bcrypt'
LoadError: cannot load such file -- bcrypt_ext
        from C:/Ruby/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        from C:/Ruby/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        from C:/Ruby/lib/ruby/gems/2.2.0/gems/bcrypt-3.1.10-x86-mingw32/lib/bcrypt.rb:16:in `rescue in <top (required)>'
        from C:/Ruby/lib/ruby/gems/2.2.0/gems/bcrypt-3.1.10-x86-mingw32/lib/bcrypt.rb:12:in `<top (required)>'
        from C:/Ruby/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:128:in `require'
        from C:/Ruby/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:128:in `rescue in require'
        from C:/Ruby/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:39:in `require'
        from (irb):1
        from C:/Ruby/bin/irb:11:in `<main>'
```

**Comment by TaylorHuston** [comment]
I'm having the same issue

**Comment by topac** [comment]
@TaylorHuston The dirty quick workaround is to install the mri version with `gem install bcrypt --platform=ruby`

**Comment by ccoenen** [comment]
very same thing here with bcrypt 3.1.10 on ruby 2.2.2 (more specifically Windows 8.1 64bit, ruby 2.2.2p95 32bit from rubyinstaller, Devkit loaded).

The error can be reproduced in irb without rails:

```
C:\Users\user\workspace\project\> gem install bcrypt
Fetching: bcrypt-3.1.10-x86-mingw32.gem (100%)
Successfully installed bcrypt-3.1.10-x86-mingw32
1 gem installed

C:\Users\user\workspace\project\> irb
irb(main):001:0> require 'bcrypt'
LoadError: cannot load such file -- 2.2/bcrypt_ext
        from C:/Tools/Ruby22/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        from C:/Tools/Ruby22/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        from C:/Tools/Ruby22/lib/ruby/gems/2.2.0/gems/bcrypt-ruby-3.0.1-x86-mingw32/lib/bcrypt_ext.rb:2:in `<top (required)>'
        from C:/Tools/Ruby22/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:128:in `require'
        from C:/Tools/Ruby22/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:128:in `rescue in require'
        from C:/Tools/Ruby22/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:39:in `require'
        from C:/Tools/Ruby22/lib/ruby/gems/2.2.0/gems/bcrypt-3.1.10-x86-mingw32/lib/bcrypt.rb:16:in `rescue in <top (required)>'
```

**Comment by gbisheimer** [comment]
Had the same problem and found the solution [here](https://www.alib.jp/entries/bcrypt_ext_load_error_on_ruby21x).

**Comment by kalvakotasneha** [comment]
Yes this solution worked for me too.. Thanks @gbisheimer

**Comment by ccoenen** [comment]
my japanese is somewhat rusty, and external links tend to disappear over the years. @gbisheimer  or @kalvakotasneha would you care to add the workaround in here (in english, if possible)? Thanks in advance!

**Comment by alxmcr** [comment]
Hello everyone. Good afternoon.

Is there any solution for: **`require': cannot load such file -- bcrypt_ext (LoadError)** ?

**Details:**

Name | Version
------------ | -------------
Ruby | ruby 2.2.3p173 (2015-08-18 revision 51636) [i386-mingw32]
Ruby on Rails | Rails 4.2.4
gem | 2.4.8
(Database) gem 'mysql2' | '~> 0.3.18'
(Server) gem 'puma ' | '2.14.0'

**Note.** I am using **Dev Kit**.
I was trying the following, in **Windows 7 (32-bit)**:

1)  ```gem 'bcrypt'```

**Error output terminal:**

```
$ rails s
C:/Ruby22/lib/ruby/gems/2.2.0/gems/bcrypt-3.1.10-x86-mingw32/lib/bcrypt.rb:16:in `require': cannot load such file -- bcrypt_ext (LoadError)
        from C:/Ruby22/lib/ruby/gems/2.2.0/gems/bcrypt-3.1.10-x86-mingw32/lib/bcrypt.rb:16:in `rescue in <top (required)>'
        from C:/Ruby22/lib/ruby/gems/2.2.0/gems/bcrypt-3.1.10-x86-mingw32/lib/bcrypt.rb:12:in `<top (required)>'
        from C:/Ruby22/lib/ruby/gems/2.2.0/gems/bundler-1.10.6/lib/bundler/runtime.rb:76:in `require'
        from C:/Ruby22/lib/ruby/gems/2.2.0/gems/bundler-1.10.6/lib/bundler/runtime.rb:76:in `block (2 levels) in require'
        from C:/Ruby22/lib/ruby/gems/2.2.0/gems/bundler-1.10.6/lib/bundler/runtime.rb:72:in `each'
        from C:/Ruby22/lib/ruby/gems/2.2.0/gems/bundler-1.10.6/lib/bundler/runtime.rb:72:in `block in require'
        from C:/Ruby22/lib/ruby/gems/2.2.0/gems/bundler-1.10.6/lib/bundler/runtime.rb:61:in `each'
        from C:/Ruby22/lib/ruby/gems/2.2.0/gems/bundler-1.10.6/lib/bundler/runtime.rb:61:in `require'
        from C:/Ruby22/lib/ruby/gems/2.2.0/gems/bundler-1.10.6/lib/bundler.rb:134:in `require'
        from E:/Mis Documentos/Alejandro/MyRepos_Github/miautenticacion/config/application.rb:7:in `<top (required)>'
        from C:/Ruby22/lib/ruby/gems/2.2.0/gems/railties-4.2.4/lib/rails/commands/commands_tasks.rb:78:in `require'
        from C:/Ruby22/lib/ruby/gems/2.2.0/gems/railties-4.2.4/lib/rails/commands/commands_tasks.rb:78:in `block in server'
        from C:/Ruby22/lib/ruby/gems/2.2.0/gems/railties-4.2.4/lib/rails/commands/commands_tasks.rb:75:in `tap'
        from C:/Ruby22/lib/ruby/gems/2.2.0/gems/railties-4.2.4/lib/rails/commands/commands_tasks.rb:75:in `server'
        from C:/Ruby22/lib/ruby/gems/2.2.0/gems/railties-4.2.4/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
        from C:/Ruby22/lib/ruby/gems/2.2.0/gems/railties-4.2.4/lib/rails/commands.rb:17:in `<top (required)>'
        from bin/rails:4:in `require'
        from bin/rails:4:in `<main>'
```

2) ```gem 'bcrypt-ruby', '3.1.1.rc1'```

**Error output terminal:**

```
$ rails s
=> Booting Puma
=> Rails 4.2.4 application starting in development on http://localhost:3000
=> Run `rails server -h` for more startup options
=> Ctrl-C to shutdown server
Puma 2.14.0 starting...
* Min threads: 0, max threads: 16
* Environment: development
* Listening on tcp://localhost:3000
```
**Browser:** [http://localhost:3000/signup](http://localhost:3000/signup)

![Browser](http://s19.postimg.org/7z9r76ukj/error_bcypt.jpg)

```
The specified module could not be found. C:/Ruby22/lib/ruby/gems/2.2.0/gems/bcrypt-ruby-3.1.1.rc1-x86-mingw32/lib/bcrypt_ext.so
```

**Error output terminal:**

```
$ rails s
=> Booting Puma
=> Rails 4.2.4 application starting in development on http://localhost:3000
=> Run `rails server -h` for more startup options
=> Ctrl-C to shutdown server
Puma 2.14.0 starting...
* Min threads: 0, max threads: 16
* Environment: development
* Listening on tcp://localhost:3000


Started GET "/" for ::1 at 2015-10-18 00:11:16 -0400
  ActiveRecord::SchemaMigration Load (0.0ms)  SELECT `schema_migrations`.* FROM `schema_migrations`
Processing by Rails::WelcomeController#index as HTML
  Rendered C:/Ruby22/lib/ruby/gems/2.2.0/gems/railties-4.2.4/lib/rails/templates/rails/welcome/index.html.erb (3.0ms)
Completed 200 OK in 58ms (Views: 43.9ms | ActiveRecord: 0.0ms)


Started GET "/signup" for ::1 at 2015-10-18 00:11:21 -0400
Processing by UsersController#new as HTML
You don't have bcrypt installed in your application. Please add it to your Gemfile and run bundle install
Completed 500 Internal Server Error in 20ms (ActiveRecord: 0.0ms)

LoadError (126: No se puede encontrar el módulo especificado.   - C:/Ruby22/lib/ruby/gems/2.2.0/gems/bcrypt-ruby-3.1.1.rc1-x86-mingw32/lib/bcrypt_ext.so):
  app/models/user.rb:2:in `<class:User>'
  app/models/user.rb:1:in `<top (required)>'
  app/controllers/users_controller.rb:3:in `new'


  Rendered C:/Ruby22/lib/ruby/gems/2.2.0/gems/actionpack-4.2.4/lib/action_dispatch/middleware/templates/rescues/_source.erb (1.0ms)
  Rendered C:/Ruby22/lib/ruby/gems/2.2.0/gems/actionpack-4.2.4/lib/action_dispatch/middleware/templates/rescues/_trace.html.erb (3.0ms)
  Rendered C:/Ruby22/lib/ruby/gems/2.2.0/gems/actionpack-4.2.4/lib/action_dispatch/middleware/templates/rescues/_request_and_response.html.erb (1.0ms)
  Rendered C:/Ruby22/lib/ruby/gems/2.2.0/gems/actionpack-4.2.4/lib/action_dispatch/middleware/templates/rescues/diagnostics.html.erb within rescues/layout (728.0ms)
  Rendered C:/Ruby22/lib/ruby/gems/2.2.0/gems/web-console-2.2.1/lib/web_console/templates/_markup.html.erb (0.0ms)
  Rendered C:/Ruby22/lib/ruby/gems/2.2.0/gems/web-console-2.2.1/lib/web_console/templates/_inner_console_markup.html.erb within layouts/inlined_string (0.0ms)
  Rendered C:/Ruby22/lib/ruby/gems/2.2.0/gems/web-console-2.2.1/lib/web_console/templates/_prompt_box_markup.html.erb within layouts/inlined_string (0.0ms)
  Rendered C:/Ruby22/lib/ruby/gems/2.2.0/gems/web-console-2.2.1/lib/web_console/templates/style.css.erb within layouts/inlined_string (0.0ms)
  Rendered C:/Ruby22/lib/ruby/gems/2.2.0/gems/web-console-2.2.1/lib/web_console/templates/console.js.erb within layouts/javascript (670.0ms)
  Rendered C:/Ruby22/lib/ruby/gems/2.2.0/gems/web-console-2.2.1/lib/web_console/templates/main.js.erb within layouts/javascript (1.0ms)
  Rendered C:/Ruby22/lib/ruby/gems/2.2.0/gems/web-console-2.2.1/lib/web_console/templates/error_page.js.erb within layouts/javascript (1.0ms)
  Rendered C:/Ruby22/lib/ruby/gems/2.2.0/gems/web-console-2.2.1/lib/web_console/templates/index.html.erb (1541.1ms)
```

*Please, I would appreciate help me solve this problem.*

**Comment by RemsonIO** [comment]
I have the same issues too with @ccoenen 
using

    gem 'bcrypt', '~> 3.1', '>= 3.1.10'

load error shows on irb too
But when I use

    gem 'bcrypt-ruby'

it loads normally while the error appears again once i started the /login page
i tried doing the one with make command but it shows me this error

    Makefile:34: *** multiple target patterns.  Stop.

**Comment by alxmcr** [comment]
Good evening. @RemsonIO , thanks for answering, then: **Is there not a complete and definitive solution to the problem?**

**Comment by ccoenen** [comment]
@gbisheimer apparently posted a solution, but it is (quite literally) japanese to me. If someone's japanese (or ruby) is good enough I'd appreciate a translation.

**Comment by alxmcr** [comment]
Hello @gbisheimer, please, can you help me? How I can do to me that Windows recognizes the **make** command? What steps did you follow to achieve?

**Comment by gbisheimer** [comment]
I have just followed this commands:
```
C:\> gem install --no-ri --no-rdoc bcrypt
```

This installs the gem in the local gem repository. Then you need to build some things.

```
C:\> cd (path to gems root)\bcrypt-3.1.7-x86-mingw32\ext\mri
C:\(path to gems root)\bcrypt-3.1.7-x86-mingw32\ext\mri> ruby extconf.rb
C:\(path to gems root)\bcrypt-3.1.7-x86-mingw32\ext\mri> make
C:\(path to gems root)\bcrypt-3.1.7-x86-mingw32\ext\mri> make install
```

That should be it.

Remember you can always use [google translate](https://translate.google.com/translate?hl=es&sl=ja&tl=en&u=https%3A%2F%2Fwww.alib.jp%2Fentries%2Fbcrypt_ext_load_error_on_ruby21x) ;)

**Comment by alxmcr** [comment]
Hello @gbisheimer. Good afternoon. 

**Details:**

Name | Version
------------ | -------------
Ruby | ruby 2.2.3p173 (2015-08-18 revision 51636) [i386-mingw32]
Ruby on Rails | Rails 4.2.4
gem | 2.4.8
(Database) gem 'mysql2' | '~> 0.3.18'
(Server) gem 'puma ' | '2.14.0'

**Note.** I am using **Dev Kit**.
I was trying the following, in **Windows 7 (32-bit)**:

****(bcrypt-3.1.7-x86-mingw32) Run the command 'ruby extconf.rb' :****

```
 C:\Ruby22\lib\ruby\gems\2.2.0\gems\bcrypt-3.1.7-x86-mingw32\ext\mri
$ ruby extconf.rb
checking for ruby/util.h... *** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
        --with-opt-dir
        --without-opt-dir
        --with-opt-include
        --without-opt-include=${opt-dir}/include
        --with-opt-lib
        --without-opt-lib=${opt-dir}/lib
        --with-make-prog
        --without-make-prog
        --srcdir=.
        --curdir
        --ruby=C:/Ruby22/bin/$(RUBY_BASE_NAME)
C:/Ruby22/lib/ruby/2.2.0/mkmf.rb:456:in `try_do': The compiler failed to generate an executable file. (RuntimeError)
You have to install development tools first.
        from C:/Ruby22/lib/ruby/2.2.0/mkmf.rb:587:in `try_cpp'
        from C:/Ruby22/lib/ruby/2.2.0/mkmf.rb:1060:in `block in have_header'
        from C:/Ruby22/lib/ruby/2.2.0/mkmf.rb:911:in `block in checking_for'
        from C:/Ruby22/lib/ruby/2.2.0/mkmf.rb:351:in `block (2 levels) in postpone'
        from C:/Ruby22/lib/ruby/2.2.0/mkmf.rb:321:in `open'
        from C:/Ruby22/lib/ruby/2.2.0/mkmf.rb:351:in `block in postpone'
        from C:/Ruby22/lib/ruby/2.2.0/mkmf.rb:321:in `open'
        from C:/Ruby22/lib/ruby/2.2.0/mkmf.rb:347:in `postpone'
        from C:/Ruby22/lib/ruby/2.2.0/mkmf.rb:910:in `checking_for'
        from C:/Ruby22/lib/ruby/2.2.0/mkmf.rb:1059:in `have_header'
        from extconf.rb:14:in `<main>'
```

**(bcrypt-3.1.10-x86-mingw32) Run the command 'make' :**

`C:\Ruby22\lib\ruby\gems\2.2.0\gems\bcrypt-3.1.10-x86-mingw32\ext\mri> make`

**He gave me the following error:**

`make: *** No rule to make target `/C/Ruby22/include/ruby-2.2.0/ruby.h', needed by `bcrypt_ext.o'.  High.`

***Do you know any reason for the error? Please. Can I help you solve the problem?***

**Comment by ccoenen** [comment]
@gbisheimer I wonder why it installed bcrypt 3.1.7 on your machine when 3.1.10 is the up to date version. Still: i have taken [the steps you translated (THANKS!)](https://github.com/codahale/bcrypt-ruby/issues/116#issuecomment-150251577) and tried them on my machine.

I can confirm that **these steps work** on a Windows 7 machine with Ruby 2.2.2p95 (32bit) from RubyInstaller and after loading the RubyDevKit-4.7.2-32bit.

Thank you!

**Comment by alxmcr** [comment]
Hello everyone, Good afternoon.

**Details:**

Name | Version
------------ | -------------
Ruby | ruby 2.2.3p173 (2015-08-18 revision 51636) [i386-mingw32]
Ruby on Rails | Rails 4.2.4
gem | 2.4.8
DevKit | 4.7.2

**Note.** I am using **Dev Kit**.
I was trying the following, in **Windows 7 (32-bit)**:

I followed the steps indicated by @gbisheimer and @ccoenen , but I get the following result:

![Error when the 'make' command runs on Windows.](http://s19.postimg.org/mb22v9zk3/error_make_command_windows.jpg)

The complete file **ruby.h** are here: [ruby.h](https://gist.github.com/alxmcr/03dd014d7f5cfa2730d4)

**Note.-** To use the **make** command in Windows, I followed these steps:

1.- Download [Make for Windows - Complete package, except sources](http://gnuwin32.sourceforge.net/packages/make.htm)

2.- Copy the following files:

* make.exe
* libintl3.dll
* libiconv2.dll

In the folder:: `C:\Ruby22\lib\ruby\gems\2.2.0\gems\bcrypt-3.1.10-x86-mingw32\ext\mri`

Please, **Can you help me ?, Could have done something wrong with using the MAKE command?** 

**Is there another way to set the "make" command in Windows?** 
**Sorry, I have no experience with the 'make' command.**

**Comment by gbisheimer** [comment]
@alxmcr, you don't need to download external make for Windows. If you are using ruby for windows and have downloaded ruby devkit, make is already included.

Before calling make, just make sure you run the file `devkitvars.bat` located on devkit install folder. This will configure the correct environment to work with ruby devkit.

Then you can run `make` and `make install` again. It should work.

No dudes en consultarme nuevamente si tienes alguna duda. Suerte!

**Comment by alxmcr** [comment]
Thanks @gbisheimer for the encouragement and support.

I followed your advice. Locate and **run the file**:

`devkitvars.bat``

and so it is configured correctly the command **make**. Then followed the commands you entered in the 
[Solution Post](https://github.com/codahale/bcrypt-ruby/issues/116#issuecomment-150251577) and everything worked out great. 

Thank you very much for sharing the solution.

**Comment by RemsonIO** [comment]
even though i run devkitvars,bat, i still dont get the 'make' command on my comman prompt. Good thing the devkit has a msys.bat which i used for the bcrypt makefile . Thank you for the responses

**Comment by codelearner777** [comment]
hello,

I am facing the same problem.
I have run the devkitvars.bat
![image](https://cloud.githubusercontent.com/assets/14092572/10903819/816f06a0-8240-11e5-9a94-2b281441ff4c.png)

but still cannot run make in the ruby root directory.
![image](https://cloud.githubusercontent.com/assets/14092572/10903845/a7d129fe-8240-11e5-9d9f-b33a5239a293.png)

could someone show where I did wrong?

**Comment by richpeck** [comment]
@gbisheimer thank you, that link worked for me

**Comment by richpeck** [comment]
For anyone getting `make` errors - you must know that in order to *build* from a `Makefile`, you need to use `make.exe`.

The `devkit` comes with `make.exe` already -- you need to [add the `devkit/bin` and `devkit/mingw/bin` paths to your `PATH` var](http://www.computerhope.com/issues/ch000549.htm).

This will allow you to call `make` in your cmd.

You then need to `cd` into your gem dir and type `make`. This will build the makefile.

**Comment by JohnMHV** [comment]
Thank you @gbisheimer. Your solution works for me.

**Comment by geekabhinav** [comment]
Thanks @gbisheimer. It worked for me on Windows 8.1, running ruby 2.2.3p173 (2015-08-18 revision 51636) [x64-mingw32]

**Comment by danilotorchio** [comment]
Hello everyone.

I went through the same problem here and I have no idea why this happens. I'll be glad to know why.
So, I just removed the Gemfile.lock and reinstalled bcrypt. After running "bundle install" again the problem doesn't happen.

Certainly you tried to do this. Works for me.

P.S.: Sorry for the bad english.

**Comment by jstdoit** [comment]
It worked for my. My env is : win8 + ruby 2.2

**Comment by Kalinon** [comment]
I know this is closed, but i encountered the same error on bcrypt 3.1.10 

Environment: 

    Windows 10 x64  
    bcrypt (3.1.10 x64-mingw32)  
    ruby 2.2.3p173 (2015-08-18 revision 51636) [x64-mingw32]  
    Rails 4.2.5 

Error Log:

    rake aborted!
    LoadError: cannot load such file -- bcrypt_ext
    C:/Users/***/Documents/***/app/services/create_admin_service.rb:4:in `block in call'
    C:in `find_or_create_by!'
    C:/Users/***/Documents/***/app/services/create_admin_service.rb:3:in `call'
    C:/Users/***/Documents/***/db/seeds.rb:8:in `<top (required)>'
    -e:1:in `load'
    -e:1:in `<main>'
    LoadError: cannot load such file -- 2.2/bcrypt_ext
    C:/Users/***/Documents/***/app/services/create_admin_service.rb:4:in `block in call'
    C:in `find_or_create_by!'
    C:/Users/***/Documents/***/app/services/create_admin_service.rb:3:in `call'
    C:/Users/***/Documents/***/db/seeds.rb:8:in `<top (required)>'
    -e:1:in `load'
    -e:1:in `<main>'
    Tasks: TOP => db:setup => db:seed
    (See full trace by running task with --trace)

**Comment by jens-a-e** [comment]
Same issue over here (Windows 10, Ruby 2.2.0 x64)

**Comment by ccoenen** [comment]
@Kalinon @jens-a-e can you confirm that you followed the [steps described earlier in this thread](https://github.com/codahale/bcrypt-ruby/issues/116#issuecomment-150251577) ?

After that, i can successfully `require 'bcrypt'` on windows 10 with ruby 2.2.3 32bit and also on ruby 2.2.3 64bit.

What you're describing is not new for windows 10, it's been the same issue on any ruby 2.2 on windows.

**Comment by Kalinon** [comment]
@ccoenen: i was able to resolve this. I had to manually update my paths as running the `devkitvars.bat` did not update my paths for some reason.

**Comment by jens-a-e** [comment]
@ccoenen i can confirm, that the steps are working.
how can we resolve this? i am using windows only as a build system and would love to get arround a batch file, that does this. :disappointed:

**Comment by ccoenen** [comment]
Honestly, i have no idea. From my point of view, this gem seems unmaintained. :-(

**Comment by howdoicomputer** [comment]
Since I didn't know how long it would take for a fix to come out, I documented how to solve this problem in [the development environment guide](https://github.com/sfbrigade/adopt-a-drain/wiki/Windows-Development-Environment) for a project that I have started contributing to.

Could be a reference point for anyone stumbling on this thread.

**Comment by Nick-DeSimone** [comment]
alxmcr solution above worked perfectly for me.

**Comment by cyerkovi** [comment]
Thanks for the solution @gbisheimer!  It worked for me (Windows 10, Ruby 2.2.4, bcrypt 3.1.10

**Comment by caleuanhopkins** [comment]
If anyone is still having issues with this (especially with devise) on Windows 64 bit, try installing Ruby 64 bit, then rails as a gem (rather than using the rails installer) and then add:
`gem 'bcrypt-ruby', '~> 3.0.0', :require => "bcrypt"`

You may need to change your `tzinfo-data` gem to:
`gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw]`

**Comment by pranayaryal** [comment]
That worked for me @caleuanhopkins thanks

**Comment by foxlance** [comment]
@gbisheimer suggestion worked for me but I couldn't make the ``devkitvars`` work. @RemsonIO was very helpful! This fixes the issue on my Win7 64bit + railsinstaller-3.2.0

**Comment by tjschuck** [comment]
Version 3.1.11 of the bcrypt gem was just pushed to RubyGems which should fix this issue.

You should now be able to `gem install bcrypt` on Windows with none of the above workarounds.

Thanks!

**Comment by ccoenen** [comment]
confirmed with Windows 8.1 / Ruby 2.2.4 (32bit)

Thanks!

**Comment by Nick-DeSimone** [comment]
I had successfully worked around this, but Iike leaving things clean for the person after me in this app.

I uninstalled brypt 3.1.10 (with the workaround), adjusted my Gemfile.lock, and ran "bundle install"

It worked perfect on:
- Windows 10
- ruby 2.2.3p173 (2015-08-18 revision 51636) [x64-mingw32]
- Rails 4.2.5

Thanks a ton!!

**Comment by jostster** [comment]
@tjschuck this still doesn't seem to work with 3.1.11 for 64 bit. I have `gem 'bcrypt', platforms: [:ruby]` in my Gem file and it doesn't install the x64 bit with `bundle install` I have to do `gem uninstall bcrypt` then `gem install bcrypt --platform=ruby` manually after running `bundle install`

**Comment by jostster** [comment]
Looks like the exact issue is also #139. There was a PR to have a more perm fix but it seems to have not been accepted.
