### ISSUE TITLE
Bcrypt 3.1.11 - Cannot load file on Windows

### ISSUE THREAD

**Issue by AliOsm** [codahale/bcrypt-ruby#142]
Bcrypt stoped working for everything i am using in my app, in my case gems like Devise are dependant of bcrypt, and them are not working anymore.

For the purpose of showing the error to you, i just create a new app named test-a, uncomment the Gemfile line

```
gem 'bcrypt', '~> 3.1.7'
```

Then run command

```
bundle install
```

And trying to start the server

```
rails s
```

It explodes bad time! With the error

```
C:/Ruby23/lib/ruby/gems/2.3.0/gems/bcrypt-3.1.11-x86-mingw32/lib/bcrypt.rb:16:in `require': cannot load such file -- bcrypt_ext (LoadError)
```

This is the screenshot

<img src="http://i.imgur.com/dFS3mwn.png"/>

I am using the next:

- Windows 10 64-bit
- Rails 5.0.0.1
- ruby 2.3.1p112 (2016-04-26 revision 54768) [i386-mingw32]

Hope there is some fix for this issue soon.

**Comment by AliOsm** [comment]
I solve it with uninstall all `bcrypt` gem versions with `gem uninstall bcrypt` and select option 3 (if exist) and uninstall all `bcrypt-ruby` gem versions with `gem uninstall bcrypt-ruby` and select option 3 (if exist) then install `bcrypt` using `gem install bcrypt --platform=ruby` then add this line `gem 'bcrypt', platforms: :ruby` to `Gemfile`, that is it :D.

**Comment by naiguelsantos** [comment]
no meu caso, eu desinstalei todas as versões do bcrypt , com gem uninstall bcrypt e seleciona opção 3 (se existir) e desisntalei todas as versões do bcrypt-ruby gem com gem uninstall bcrypt-ruby e seleciona opção 3 (se existir), depois instalei o bcrypt usando gem install bcrypt --platform=ruby e adicionei esta linha gem 'bcrypt', '~> 3.1.7' no Gemfile. Funcionou certinho.

**Comment by naiguelsantos** [comment]
In my case, I uninstalled all versions of bcrypt, with gem uninstall bcrypt and select option 3 (if it exists), and uninstalled all versions of bcrypt-ruby gem with gem uninstall bcrypt-ruby and select option 3 (if it exists), then I installed bcrypt using gem install bcrypt --platform = ruby and I added this line gem 'bcrypt', '~> 3.1.7' in Gemfile. It worked right.

**Comment by rodrigopk** [comment]
I also solved this by uninstalling bcrypt and re-installing it using the --platform=ruby parameter, but here follows a command to remove the gems that depend on bcrypt in case anyone runs into the same problem as me (gem Uninstallation aborted due to dependent gem(s)):
`gem list bcrypt | cut -d" " -f1 | xargs gem uninstall -aIx`

**Comment by alexakasanjeev** [comment]
Thank you so much finally, something worked, but what was the issue causing it?

**Comment by pranjal815** [comment]
Thank you so much @AliOsm I finally able to resolve the issue.

**Comment by michael-wise** [comment]
As shown in https://github.com/codahale/bcrypt-ruby/issues/102#issuecomment-284118731, pointing the gemfile to the git repo seems to be working nowadays. That is, `gem 'bcrypt', git: 'https://github.com/codahale/bcrypt-ruby.git', :require => 'bcrypt'`

**Comment by stonewallthomas** [comment]
Gees, thank you so much.  I spent over an hour on this yesterday, and this actually worked!  I followed so many bogus procedures in different forums.  It was this simple for me:

I have Windows 7 64, Ruby 2.3.3, Rails 5.0.2

I did this in terminal in my project root:
gem uninstall bcrypt-ruby
gem uninstall bcrypt
gem install bcrypt

Then added this to my Gemfile:
gem 'bcrypt', '~> 3.1.7'

Although my version of bycrypt was 3.1.11, this worked just fine.

**Comment by gregkin** [comment]
Why would this cure the problem?  Pointing the gem at the git site.  Why won't the rubygems install
work.  I did use the git site and my problem is solved.  Just trying to understand!
gem 'bcrypt', git: 'https://github.com/codahale/bcrypt-ruby.git', :require => 'bcrypt'

**Comment by zLooey** [comment]
@naiguelsantos Thank you man, you saved my life, although I had to delete the Gemfile.lock before running the codes you said, but after all it worked.

**Comment by busterb** [comment]
Hi @codahale - since this issue appears to be resolved in master, could you please release an update to rubygems? Looks like the last public release was in 2014

**Comment by TheChisus** [comment]
Tried almost everything here and nada. I stumbled on https://stackoverflow.com/questions/33588735/loaderror-cannot-load-such-file-bcrypt-ext-on-windows-2008-x64-server and the first  answer (answer with most votes) solved it!

**Comment by Adilkemo** [comment]
thank you a lot Mr.@stonewallthomas your solutions is work on me

**Comment by dominiccodes** [comment]
Thanks stonewallthomas  and gregkin

**Comment by pr-201** [comment]
helped @stonewallthomas method, thanks!

**Comment by cahyowhy** [comment]
gem install bcrypt --platform=ruby, raise an error to my terminal

```
ERROR:  Error installing bcrypt:                                                                            
        ERROR: Failed to build gem native extension.                                                        
                                                                                                            
    current directory: C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/bcrypt-3.1.11/ext/mri                         
C:/Ruby23-x64/bin/ruby.exe -r ./siteconf20170815-5012-xduvqg.rb extconf.rb                                  
creating Makefile                                                                                           
                                                                                                            
current directory: C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/bcrypt-3.1.11/ext/mri                             
make "DESTDIR=" clean                                                                                       
                                                                                                            
current directory: C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/bcrypt-3.1.11/ext/mri                             
make "DESTDIR="                                                                                             
generating bcrypt_ext-x64-mingw32.def                                                                       
make: *** No rule to make target `/C/Ruby23-x64/include/ruby-2.3.0/ruby.h', needed by `bcrypt_ext.o'.  Stop.
                                                                                                            
make failed, exit code 2                                                                                    
                                                                                                            
Gem files will remain installed in C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/bcrypt-3.1.11 for inspection.     
Results logged to C:/Ruby23-x64/lib/ruby/gems/2.3.0/extensions/x64-mingw32/2.3.0/bcrypt-3.1.11/gem_make.out 
```

**Comment by GuilleBecker15** [comment]
@stonewallthomas your method work for me, thanks!

**Comment by isabelle-me** [comment]
@stonewallthomas your method work for me, thanks!

**Comment by taab84** [comment]
@naiguelsantos your method worked for me, thank you

**Comment by michael-wise** [comment]
> Why would this cure the problem? Pointing the gem at the git site. Why won't the rubygems install work.

@gregkin If you check rubygems, the [latest ruby-bcrypt gem is from 2014](https://rubygems.org/gems/bcrypt-ruby/versions/3.1.5). Pointing the gemfile explicitly to the bcrypt-ruby git repository pulls a far more recent version.

**Comment by michael-wise** [comment]
@stonewallthomas /**everyone** I think I like this solution more, as it pulls from the bcrypt gem instead of bcrypt-ruby. The bcrypt gem is somewhat updated ~2016 (compared to bcrypt-ruby gem ~2014), and it is probably  better for gemfile versioning as well--I haven't looked into how the gemfile deals with versioning for git sources.

**Comment by Gchicaduque83** [comment]
I did this in terminal in my project root:
gem uninstall bcrypt-ruby
gem uninstall bcrypt
gem install bcrypt --platform=ruby

Then added this to my Gemfile:
gem 'bcrypt', '~> 3.1.11'

And of course:
bundle install

Finally
rails restart

**Comment by Luippo** [comment]
@AliOsm thanks, your answer was usefull to me!!

**Comment by insub** [comment]
Everytime i changed the gemfile.rb and bundle install, the error:"Bcrypt 3.1.11 - Cannot load file on Windows" showed.
Then i had to input "gem uninstall bcrypt" and "gem install bcrypt --platform=ruby" again.
Any idea?

**Comment by AliOsm** [comment]
@insub add `gem 'bcrypt', platforms: :ruby` to the Gemfile and then `bundle install` well work without errors.

**Comment by Labrat02** [comment]
@AliOsm  @insub is correct.  This is happening for me as well.

If I have 
gem 'bcrypt', platforms: :ruby

then bundle install will install bcrypt (3.1.11 x86-mingw32) 

gem 'bcrypt', git: 'https://github.com/codahale/bcrypt-ruby.git', require: 'bcrypt'
this seems to work, but I don't like this solution as most of my environments are in docker or mac, also it is slower to install and doesn't show up in "gem list" so I am avoiding this.

So that means I need to manually uninstall and reinstall using the --platform=ruby command which installs the normal 3.1.11 version.

Also tried 3.1.7, but this seems to revert to the x86-mingw32 version of 3.1.11 as well on Windows 10

**Comment by lunarfyre7** [comment]
`gem 'bcrypt', git: 'https://github.com/codahale/bcrypt-ruby.git', require: 'bcrypt' if Gem.win_platform? `
This is what I'm using in my gemfile, it should avoid the issues @Labrat02 mentioned by only targeting Windows.

**Comment by GabrielRMorales** [comment]
@stonewallthomas Thank you, your solution worked for me (this time, haha)!

At first the solution wasn't working. I deleted the Gemfile.lock before, then followed the steps. Also, I included gem 'bcrypt', git: 'https://github.com/codahale/bcrypt-ruby.git', :require => 'bcrypt' in the Gemfile before bundle install. Then did rails restart.

This was on a Windows 7 64, Ruby 2.3.3, Rails 5.0.6

**Comment by k0sstik** [comment]
Great! Thx gees! 
I use devise and had this problem too when i try ro sign_up in my web-application! 

but this is fix problem:
gem uninstall bcrypt-ruby
gem uninstall bcrypt
gem install bcrypt --platform=ruby

**Comment by monkeysuffrage** [comment]
This isn't working for me, any ideas?
owner@WINDOWS-PC ~: gem install bcrypt --platform=ruby
ERROR:  While executing gem ... (Gem::UnsatisfiableDependencyError)
    Unable to resolve dependency: No match for 'psych (= 3.0.1)' on this platform. Found: x64-mingw32

**Comment by wallwood** [comment]
This isnt work for me also

 rails s
C:/RailsInstaller/Ruby2.3.3/lib/ruby/gems/2.3.0/gems/bcrypt-3.1.11-x86-mingw32/lib/bcrypt.rb:16:in `require': cannot load such file -- bcrypt_ext (LoadError)
        from C:/RailsInstaller/Ruby2.3.3/lib/ruby/gems/2.3.0/gems/bcrypt-3.1.11-x86-mingw32/lib/bcrypt.rb:16:in `rescue in <top (required)>'
        from C:/RailsInstaller/Ruby2.3.3/lib/ruby/gems/2.3.0/gems/bcrypt-3.1.11-x86-mingw32/lib/bcrypt.rb:12:in `<top (required)>'
        from C:/RailsInstaller/Ruby2.3.3/lib/ruby/gems/2.3.0/gems/bundler-1.16.1/lib/bundler/runtime.rb:81:in `require'
        from C:/RailsInstaller/Ruby2.3.3/lib/ruby/gems/2.3.0/gems/bundler-1.16.1/lib/bundler/runtime.rb:81:in `block (2 levels) in require'
        from C:/RailsInstaller/Ruby2.3.3/lib/ruby/gems/2.3.0/gems/bundler-1.16.1/lib/bundler/runtime.rb:76:in `each'
        from C:/RailsInstaller/Ruby2.3.3/lib/ruby/gems/2.3.0/gems/bundler-1.16.1/lib/bundler/runtime.rb:76:in `block in require'
        from C:/RailsInstaller/Ruby2.3.3/lib/ruby/gems/2.3.0/gems/bundler-1.16.1/lib/bundler/runtime.rb:65:in `each'
        from C:/RailsInstaller/Ruby2.3.3/lib/ruby/gems/2.3.0/gems/bundler-1.16.1/lib/bundler/runtime.rb:65:in `require'
        from C:/RailsInstaller/Ruby2.3.3/lib/ruby/gems/2.3.0/gems/bundler-1.16.1/lib/bundler.rb:114:in `require'
        from C:/Sites/stukdo/config/application.rb:7:in `<top (required)>'
        from C:/RailsInstaller/Ruby2.3.3/lib/ruby/gems/2.3.0/gems/railties-5.1.6/lib/rails/commands/server/server_command.rb:133:in `require'
        from C:/RailsInstaller/Ruby2.3.3/lib/ruby/gems/2.3.0/gems/railties-5.1.6/lib/rails/commands/server/server_command.rb:133:in `block in perform'
        from C:/RailsInstaller/Ruby2.3.3/lib/ruby/gems/2.3.0/gems/railties-5.1.6/lib/rails/commands/server/server_command.rb:130:in `tap'
        from C:/RailsInstaller/Ruby2.3.3/lib/ruby/gems/2.3.0/gems/railties-5.1.6/lib/rails/commands/server/server_command.rb:130:in `perform'
        from C:/RailsInstaller/Ruby2.3.3/lib/ruby/gems/2.3.0/gems/thor-0.20.0/lib/thor/command.rb:27:in `run'
        from C:/RailsInstaller/Ruby2.3.3/lib/ruby/gems/2.3.0/gems/thor-0.20.0/lib/thor/invocation.rb:126:in `invoke_command'
        from C:/RailsInstaller/Ruby2.3.3/lib/ruby/gems/2.3.0/gems/thor-0.20.0/lib/thor.rb:387:in `dispatch'
        from C:/RailsInstaller/Ruby2.3.3/lib/ruby/gems/2.3.0/gems/railties-5.1.6/lib/rails/command/base.rb:63:in `perform'
        from C:/RailsInstaller/Ruby2.3.3/lib/ruby/gems/2.3.0/gems/railties-5.1.6/lib/rails/command.rb:44:in `invoke'
        from C:/RailsInstaller/Ruby2.3.3/lib/ruby/gems/2.3.0/gems/railties-5.1.6/lib/rails/commands.rb:16:in `<top (required)>'
        from bin/rails:4:in `require'
        from bin/rails:4:in `<main>'

**Comment by johnnyshields** [comment]
Bcrypt team, **please fix this issue**

**Comment by johnnyshields** [comment]
@luislavena is this something you could help with?

**Comment by luislavena** [comment]
@johnnyshields I'm no longer involved with RubyInstaller or Ruby for Windows, however the error is caused by the gem lacking binaries for newer versions of Ruby.

While you can manually force to recompile (`gem install bcrypt --platform=ruby`), Bundler might not be friendly and will always try to install the binary version instead.

@larskanis has helped other projects get better support of newer Rubies on several projects and might be able to provide some up-to-date instructions or pointers on what will be required on your end.

From the get go, this might need a new release of the gem.

Hope that helps.

Cheers.

**Comment by johnnyshields** [comment]
@luislavena thank you that's very helpful. @larskanis or someone from this project can you please help?

**Comment by wallwood** [comment]
Hello,

Its solve for me with step is below :

1. Make sure you have installed DEVKIT, as default devkit has installed in  C:\RailsInstaller\DevKits
2. Open “mingw32env.cmd", Folder : C:\RailsInstaller\DevKit\mingw
3. Change the directory to “C:\RailsInstaller\DevKit” and run "devkitvars.bat"
4. After finished step 3, change the directory to “C:\RailsInstaller\Ruby2.3.3\lib\ruby\gems\2.3.0\gems\bcrypt-3.1.11-x86-mingw32\ext\mri”
5. run “ruby extconf.rb”
6. run "make"
7. run "make isntall"
Done !
 
![image](https://user-images.githubusercontent.com/29316022/39873947-98e583e2-5496-11e8-985a-4868ac10abf7.png)

**Comment by johnnyshields** [comment]
@wallwood they need to bundle new binaries with the gem for windows. then these steps won't be needed.

**Comment by larskanis** [comment]
Thanks @luislavena for the invitation!

As far as I remember bcrypt builds fine with any RubyInstaller version, provided that DevKit is present. So you can either use
```
gem install bcrypt --platform=ruby
```
or if you're using a Gemfile than
```
gem "bcrypt", git: "https://github.com/codahale/bcrypt-ruby/"
```

Years ago I proposed #117, which would provide updated fat binary Windows gems, but to be honest, it's probably best to drop these platform specific gem versions entirely and release a platform "ruby" gem only at the next version. This always requires to have DevKit installed, but the Ruby+DevKit version is by far the most downloaded RubyInstaller flavor anyways.

This way Windows is no longer treated as a special case, which requires new releases for every new ruby version, but behaves as on all other operating systems.

**Comment by johnnyshields** [comment]
I would agree it would be best to drop the platform specific versions, as everyone on windows has devkit. Can a gem maintainer help with this?

**Comment by larskanis** [comment]
@tjschuck I tested bcrypt-3.1.12.rc1 successfully on Ruby-2.5.1-x64. However it still fails with `cannot load such file -- bcrypt_ext` on [Ruby-2.6](https://github.com/oneclick/rubyinstaller2/releases/tag/rubyinstaller-head). This is why I think it's better to [no longer release fat binary gems](https://github.com/codahale/bcrypt-ruby/issues/173).

**Comment by tjschuck** [comment]
Version 3.1.12 of the bcrypt gem, which should fix this issue, was just pushed to RubyGems.

You should now be able to `gem install bcrypt` on Windows with none of the above workarounds.

Thanks, everyone!

**Comment by baladkb** [comment]
> In my case, I uninstalled all versions of bcrypt, with gem uninstall bcrypt and select option 3 (if it exists), and uninstalled all versions of bcrypt-ruby gem with gem uninstall bcrypt-ruby and select option 3 (if it exists), then I installed bcrypt using gem install bcrypt --platform = ruby and I added this line gem 'bcrypt', '~> 3.1.7' in Gemfile. It worked right.

You saved me! :octocat:
