### ISSUE TITLE
BCrypt 3.1.11 (x86-mingw32): cannot load such file -- bcrypt_ext

### ISSUE THREAD

**Issue by TheFlow0360** [codahale/bcrypt-ruby#149]
I recently created a new Rails project after installing Ruby and Rails on Windows with RailsInstaller. In my gemfile, I reference bcrypt like this:
`gem 'bcrypt', '~> 3.1.7', platforms: :ruby` *(I added the `platforms: :ruby`, without server won't start with the same error as described further below)*

The server can be started, no problems here, but wen instantiating a model with `has_secure_password` I get the following error message:

> You don't have bcrypt installed in your application. Please add it to your Gemfile and run bundle install
> Completed 500 Internal Server Error in 16ms (ActiveRecord: 0.0ms)
> 
> 
> 
> LoadError (cannot load such file -- bcrypt_ext):
> 
> app/models/access.rb:2:in `<class:Access>'
> app/models/access.rb:1:in `<top (required)>'
> Rendering C:/RailsInstaller/Ruby2.3.0/lib/ruby/gems/2.3.0/gems/actionpack-5.0.1/lib/action_dispatch/middleware/templates/rescues/diagnostics.html.erb within rescues/layout
> Rendering C:/RailsInstaller/Ruby2.3.0/lib/ruby/gems/2.3.0/gems/actionpack-5.0.1/lib/action_dispatch/middleware/templates/rescues/_source.html.erb
> Rendered C:/RailsInstaller/Ruby2.3.0/lib/ruby/gems/2.3.0/gems/actionpack-5.0.1/lib/action_dispatch/middleware/templates/rescues/_source.html.erb (3.0ms)
> Rendering C:/RailsInstaller/Ruby2.3.0/lib/ruby/gems/2.3.0/gems/actionpack-5.0.1/lib/action_dispatch/middleware/templates/rescues/_trace.html.erb
> Rendered C:/RailsInstaller/Ruby2.3.0/lib/ruby/gems/2.3.0/gems/actionpack-5.0.1/lib/action_dispatch/middleware/templates/rescues/_trace.html.erb (1.0ms)
> Rendering C:/RailsInstaller/Ruby2.3.0/lib/ruby/gems/2.3.0/gems/actionpack-5.0.1/lib/action_dispatch/middleware/templates/rescues/_request_and_response.html.erb
> Rendered C:/RailsInstaller/Ruby2.3.0/lib/ruby/gems/2.3.0/gems/actionpack-5.0.1/lib/action_dispatch/middleware/templates/rescues/_request_and_response.html.erb (1.0ms)
> Rendered C:/RailsInstaller/Ruby2.3.0/lib/ruby/gems/2.3.0/gems/actionpack-5.0.1/lib/action_dispatch/middleware/templates/rescues/diagnostics.html.erb within rescues/layout (358.0ms)
> Exiting

I tried fixing the version of bcrypt to 3.1.9, because I found [this issue](https://github.com/codahale/bcrypt-ruby/issues/102) where a similar error occurred for the 3.1.7 and the solution was to use 3.1.9, but this didn't help at all, on the contrary: Afterwards the server wouldn't start at all.

I know there is [Issue 142](https://github.com/codahale/bcrypt-ruby/issues/142), but their solution doesn't work for me.

Does anyone have an idea how I could fix this?

**Comment by fpauser** [comment]
Same problem here...

**Comment by gvescu** [comment]
Just got this issue again. The only solution right now is to run:

```
gem uninstall bcrypt
gem install bcrypt --platform=ruby
```

I suppose it's just a temporary fix.

**Comment by TheFlow0360** [comment]
I already tried that, this doesn't fix the problem for me. I did this to be able to start the server at all, but when using my model with `has_secure_password ` the exception still occurs.

**Comment by scivola** [comment]
How about this?

```
gem list bcrypt
```

**Comment by TheFlow0360** [comment]
what about it? It outputs the gems:

> gem list bcrypt
>
> *** LOCAL GEMS ***
>
> bcrypt (3.1.11)

**Comment by scivola** [comment]
Hmm...

Are there bcrypt_ext.* in the subdirectories of C:/RailsInstaller/Ruby2.3.0/lib/ruby/gems/2.3.0/gems/bcrypt-3.1.11/ext ?

**Comment by TheFlow0360** [comment]
Subfolder `jruby`` just contains another folder `bcrypt_jruby` with a `BCrypt.java`, other folder is mri with the following content:

>  Verzeichnis von C:\RailsInstaller\Ruby2.3.0\lib\ruby\gems\2.3.0\gems\bcrypt-3.1.11\ext\mri
>
> 06.03.2017  09:50    \<DIR\>          .
> 06.03.2017  09:50    \<DIR\>          ..
> 06.03.2017  09:50                 0 .RUBYARCHDIR.time
> 06.03.2017  09:50                24 bcrypt_ext-i386-mingw32.def
> 06.03.2017  09:49             1.540 bcrypt_ext.c
> 06.03.2017  09:50             8.837 bcrypt_ext.o
> 06.03.2017  09:50            33.280 bcrypt_ext.so
> 06.03.2017  09:49             1.062 crypt.c
> 06.03.2017  09:49               268 crypt.h
> 06.03.2017  09:50             8.668 crypt.o
> 06.03.2017  09:49            26.325 crypt_blowfish.c
> 06.03.2017  09:50            74.787 crypt_blowfish.o
> 06.03.2017  09:49             3.348 crypt_gensalt.c
> 06.03.2017  09:50             4.785 crypt_gensalt.o
> 06.03.2017  09:49               417 extconf.rb
> 06.03.2017  09:49             7.941 Makefile
> 06.03.2017  09:49               998 ow-crypt.h
> 06.03.2017  09:49             7.098 wrapper.c
> 06.03.2017  09:50             8.065 wrapper.o
>               17 Datei(en),        187.443 Bytes
>                2 Verzeichnis(se), 753.023.946.752 Bytes frei

Sorry for the bad formatting, the tabs are getting truncated.

**Comment by TheFlow0360** [comment]
I just noticed, when really uninstalling and reinstalling bcrypt it works, the problem is that after running bundler install the wrong bcrypt get's installed. I just don't understand why.

Installing with `gem install bcrypt --platform=ruby` is working, and my gemfile contains `gem 'bcrypt', '~> 3.1.7', platforms: :ruby` but breaks the installation. What do I need to write there to be equivalent?

**Comment by hellrider200** [comment]
hello, just had the same problem, and solved it, with uninstall - install solution provided from [issue 142](https://github.com/codahale/bcrypt-ruby/issues/142)  The way it worked for me is in the gem file I commented out `# gem bcrypt, '3.1.11'` and run `bundle install`... after that UnCommented  ` gem 'bcrypt', '3.1.11', platforms: [:ruby, :x64_mingw] `  and again ` bundle install ` and that's it. Hope this helps someone.. 

P.S `:x64_mingw`  is  for 64x  Windows. I am on win7x64

**Comment by gaumondia** [comment]
@hellrider200 somehow that didn't work on my end and the solution listed here worked instead https://github.com/codahale/bcrypt-ruby/issues/102
Hopefully it helps someone else too!

**Comment by TheFlow0360** [comment]
@gaumondia yeah but referencing the github version isn't exactly something I want to do when the project goes into production...

**Comment by overload77** [comment]
I solved it based on hellriders solution.First of all comment out `# gem bcrypt, '3.1.11'` and run `bundle install`.After that uninstall the gem with `gem uninstall bcrypt`.Then re-install `gem install bcrypt --platform=ruby`.The **important** part, un-comment `gem 'bcrypt', '~> 3.1.11', platforms: [:ruby, :x64_mingw, :mingw]` and then bundle install.Thats it.Note the mingw part at the end.This should be the key.

**Comment by TheFlow0360** [comment]
@overload77 it seems as if this solves my problem with bundler reinstalling the wrong gem, even though I don't really understand why... thanks, anyways!

**Comment by hellrider200** [comment]
@TheFlow0360 glad you solved it as well, one thing though, now when you want to install new gem for the given project, install it with the **gem install** command, because if you do it with **bundle install** it will see the extensions/options for **bcrypt** ie.  ```platforms: [:ruby, :x64_mingw, :mingw]``` and will install the gem for those platforms meaning for  **:x64_mingw, :mingw** and it will error again
So when using **gem install**,  bundler will not *install* just **use** the new gem and it will not see the bcrypt  extensions/options... try that and tell if it worked...

**Comment by TheFlow0360** [comment]
Yeah, I did install bcrypt manually, so this may be true. But before every time I executed bundle install it still installed the wrong bcrypt on top, now it doesn't do this anymore. And you think if it's the first install this still won't work? I don't want to set up another environment just to test this right now, but if you are right this is still quite bad... The aim should be that bundler fully prepares my environment...

**Comment by michael-wise** [comment]
Yeah this is really frustrating. There are already several issues windows users face when trying to do rails development :(. I'm practicing rails development again after taking a break and remember facing this months ago. This time in opting for a simpler login system using bcrypt, the issue reappears. I tried @overload77's solution but still face the error:

> C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/bcrypt-3.1.11-x64-mingw32/lib/bcrypt.rb:16:in `require': cannot load such file -- bcrypt_ext (L
oadError)
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/bcrypt-3.1.11-x64-mingw32/lib/bcrypt.rb:16:in `rescue in <top (required)>'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/bcrypt-3.1.11-x64-mingw32/lib/bcrypt.rb:12:in `<top (required)>'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/bundler-1.14.4/lib/bundler/runtime.rb:91:in `require'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/bundler-1.14.4/lib/bundler/runtime.rb:91:in `block (2 levels) in require'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/bundler-1.14.4/lib/bundler/runtime.rb:86:in `each'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/bundler-1.14.4/lib/bundler/runtime.rb:86:in `block in require'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/bundler-1.14.4/lib/bundler/runtime.rb:75:in `each'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/bundler-1.14.4/lib/bundler/runtime.rb:75:in `require'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/bundler-1.14.4/lib/bundler.rb:107:in `require'
        from C:/sites/mleewise/config/application.rb:7:in `<top (required)>'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/railties-5.0.1/lib/rails/commands/commands_tasks.rb:88:in `require'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/railties-5.0.1/lib/rails/commands/commands_tasks.rb:88:in `block in server'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/railties-5.0.1/lib/rails/commands/commands_tasks.rb:85:in `tap'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/railties-5.0.1/lib/rails/commands/commands_tasks.rb:85:in `server'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/railties-5.0.1/lib/rails/commands/commands_tasks.rb:49:in `run_command!'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/railties-5.0.1/lib/rails/commands.rb:18:in `<top (required)>'
        from bin/rails:4:in `require'
        from bin/rails:4:in `<main>'

I would be willing to put $20 towards a bounty for a proper fix...if anyone else wants to chip in.

**Comment by TheFlow0360** [comment]
@michael-wise  did you try everything listed in this thread? I got it running, even though the solution isn't perfect because bundler won't install it correctly in a new environment. The key for me is that only the normal bcrypt gem may be installed, as soon as the mingw x86 is there it won't work anymore.

**Comment by michael-wise** [comment]
@TheFlow0360. Success--I repeated @overload77's process but replaced the Gemfile's `platforms: [:ruby, :x64_mingw, :mingw]` with `platforms [:ruby]`. 

I did this because I noticed that `gem install bcrypt --platform=ruby` and `gem list bcrypt` shows `bcrypt (3.1.11)` while `gem list bcrypt` after his instructions showed the damning `bcrypt 3.1.11 (x64-mingw32)`.

Also, as I see, the first bundle install in his instructions is redundant, as doing gem uninstall bcrypt removes the gem.

**Comment by kalyn-robinson** [comment]
@ladyruby723's solution in an earlier issue solved this for me:

```gem 'bcrypt', git: 'https://github.com/codahale/bcrypt-ruby.git', :require => 'bcrypt'```

**Comment by TheFlow0360** [comment]
@kalyn-robinson this does work for most of us, but it isn't something you really want to have for something that goes into production. Reinstall somewhere else later, und you get a different version of bcrypt? This could be bad. For bcrypt this problem may be less relevant, but in general I don't want to reference the master branch of a gem except for development or testing purposes.

**Comment by Klashe** [comment]
I solve it with uninstall all bcrypt gem versions with gem uninstall bcrypt and select option 3 (if exist) 
and uninstall all bcrypt-ruby gem versions with gem uninstall bcrypt-ruby and select option 3 (if exist).

Then added this to my gemfile gem 'bcrypt', git: 'https://github.com/codahale/bcrypt-ruby.git', :require => 'bcrypt'

**Comment by Klashe** [comment]
I solve it with uninstall all bcrypt gem versions with gem uninstall bcrypt and select option 3 (if exist) 
and uninstall all bcrypt-ruby gem versions with gem uninstall bcrypt-ruby and select option 3 (if exist).

Then added this to my gemfile gem 'bcrypt', git: 'https://github.com/codahale/bcrypt-ruby.git', :require => 'bcrypt' then bunddle install.

**Comment by Mifrill** [comment]
- git clone https://github.com/codahale/bcrypt-ruby.git
  - cd bcrypt-ruby
  - gem build bcrypt.gemspec
  - gem install gem-compiler
  - gem compile bcrypt-3.1.11.gem
  - gem install ./bcrypt-3.1.11-x86-mingw32.gem

**Comment by wsmithsrs** [comment]
I was having this issue and managed to fix it by uninstalling bcrypt with `gem uninstall bcrypt` and removing it from my Gemfile. I believe the problem was being caused by another conflicting gem that uses bcrypt.

**Comment by daffe1er** [comment]
I have the same problem  like TheFlow0360. i have done all that is done but the problem is reoccuring, can you help please

C:\Users\DAFFE.DAFFE>rake dev_data:create
rake aborted!
No Rakefile found (looking for: rakefile, Rakefile, rakefile.rb, Rakefile.rb)

(See full trace by running task with --trace)

C:\Users\DAFFE.DAFFE>cd challenger

C:\Users\DAFFE.DAFFE\challenger>rake dev_data:create
rake aborted!
LoadError: cannot load such file -- bcrypt
C:/Users/DAFFE.DAFFE/challenger/app/models/user.rb:1:in `<top (required)>'
C:/Users/DAFFE.DAFFE/challenger/lib/tasks/dev_data.rake:9:in `block (2 levels) in <top (required)>'
Tasks: TOP => dev_data:create
(See full trace by running task with --trace)

C:\Users\DAFFE.DAFFE\challenger>bundle list bcrypt
Could not find gem 'bcrypt'.

C:\Users\DAFFE.DAFFE\challenger>gem list bcrypt

*** LOCAL GEMS ***

bcrypt (3.1.11 x64-mingw32)

**Comment by zinderud** [comment]
I   temporary fix.
gem uninstall bcrypt
gem install bcrypt --platform=ruby
but all  new  add gem  conflicting   and again..

**Comment by johnnyshields** [comment]
@tjschuck what's the plan to fix this? Issue has been out there for quite a long time now and is an annoyance for all Windows users

**Comment by GizellySteffanny** [comment]
gem list bcrypt
gem uninstall bcrypt
gem install bcrypt --platform=ruby

**Comment by johnnyshields** [comment]
@GizellySteffanny that's the workaround. You need to run this after every bundle install/upgrade because Bcrypt mingw gets reinstalled.

**Comment by Tommyleerom** [comment]
Is there any solution that for good and all fix the problem on windows?

**Comment by bodrovis** [comment]
AFAIK, the only solution to fix this problem once and for all is rebuild the gem locally. Perform the following steps:

1. You need DevKit or MSYS (for newer Rubies) installed that can be taken from RubyInstaller site (MSYS is actually integrated into newer Ruby installers). Note that in case of DevKit the `PATH` should also contain `c:\devkit\mingw\bin` path (that has `make.exe` file)!
2. Next, open up terminal and `cd` into the directory where BCrypt files reside. Something like `c:\Ruby24\lib\ruby\gems\2.2.4\gems\bcrypt-3.1.11-x64-mingw32\ext\mri`
3. Here, run `ruby extconf.rb`
4. Then `make`
5. Then `make install`
6. After this is done the problem should be fixed (also you might want to `bundle install` just in case). You don't need to add any `platform: :ruby` stuff to the Gemfile for bcrypt.

**Note** that steps 4 and 5 should be performed from *MSYS command line interface if you are not using DevKit* (that is, for newer Rubies)! In order to properly open this terminal run `F:\msys64\msys2_shell.cmd -mingw64` (if you're using Windows x64). Hopefully this helps, and best of luck.

**Comment by vatanbytyqi** [comment]
Hi,
I'm still having this issue on my windows. I run **windows 10** and use the **railsinstaller 3.4.0** (which includes **ruby 2.3.3**).
I get the error `LoadError (cannot load such file -- bcrypt_ext):` when I log in to my site and not when the server is started. 

I use Devise gem which installs `bcrypt-3.1.11-x86-mingw32` when I run `gem install Devise`, and I'm required to uninstall Devise before I can uninstall bcrypt due to dependency issue. Why does not the same solution work with my setup?

**Comment by Tommyleerom** [comment]
@bodrovis thanks man :) your solution works for me (windows 7- x64)

**Comment by ohiodn8** [comment]
(No issue on Linux but every time I moved to Windows, I'll get the error). _gem uninstall bcrypt_ and _gem install bcrypt --platform=ruby_ was a temporary fix, broke after _bundle install_. 

##  My Fix =>
**gemfile.lock:** 
(Delete bcrypt from gemfile.lock)
Downgrade devise to: 
    _devise (4.3)
      bcrypt (~> 3.0)_
< scroll down to DEPENDENCIES >
_DEPENDENCIES
  bcrypt!
  devise (~> 4.3)_
**Gemfile:**
_gem 'devise', '~> 4.3'
gem 'bcrypt', git: 'https://github.com/codahale/bcrypt-ruby.git', :require => 'bcrypt'_

**To commandline:**
`gem uninstall bcrypt`
`bundle install`

**Comment by Holmesmichael** [comment]
@ohiodn8  Your solution is the only one that would work.  I can now move forward with my project, thanks.

**Comment by aashishg** [comment]
@ohiodn8 Works! Thanks!

**Comment by ChrisCavs** [comment]
You may have tried this already, but after install bcrypt you have to restart your server.  Had the same issue you described, and nothing worked for me unless I restarted server after each install.  Hope it helps.

**Comment by johnnyshields** [comment]
^^^ yes we all know the workaround. we want the real issue to be fixed!

**Comment by cocaholic-communist** [comment]
Despite using and following all the methods you all suggested, I am unable to use crypt successfully.
p.s.:I have installed and uninstalled bcrypt gem for almost a day and it still failed to work.

**Comment by cocaholic-communist** [comment]
I have also been taking measures,for example, I restarted the server, changed the gem, install and uninstalled the gem and so on and so forth.This is indeed frustrating and unbelievable.I hope action would be taken with immediate effect.Thank you.

**Comment by tjschuck** [comment]
I have just pushed version 3.1.12.rc1 to RubyGems.org which should solve this problem.

Can someone please confirm that `gem install bcrypt --prerelease` now works on Fedora 28?  If so, I'll push out the final version.

**Comment by tjschuck** [comment]
Version 3.1.12 of the bcrypt gem, which should fix this issue, was just pushed to RubyGems.

You should now be able to `gem install bcrypt` on Windows with none of the above workarounds.

Thanks, everyone!
